<?php
/**
 * @file
 * Page Manager bridge for rendered node reference field formatter.
 */

/**
 * Implements hook_field_formatter_info_alter().
 */
function node_reference_page_manager_bridge_field_formatter_info_alter(&$info) {
  if(module_exists('page_manager')) {
    $info['node_reference_node']['module'] = 'node_reference_page_manager_bridge';
  }
}

/**
 * Implements hook_field_formatter_prepare_view().
 */
function node_reference_page_manager_bridge_field_formatter_prepare_view($entity_type, $entities, $field, $instances, $langcode, &$items, $displays) {
  node_reference_field_formatter_prepare_view($entity_type, $entities, $field, $instances, $langcode, $items, $displays);
}

/**
 * Implements hook_field_formatter_view().
 */
function node_reference_page_manager_bridge_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  foreach($items as $delta => $item) {
    if($item['access']) {

      if(function_exists('page_manager_node_view_page')) {
        $markup = page_manager_node_view_page($item['node']);
      } else {
        $markup = node_page_view($item['node']);
      }
      
      $element[$delta] = (is_array($markup)) ? $markup : array('#markup' => $markup);
    }
  }

  return $element;
}